name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Ensure the 'out' directory exists
          if [ -d "out" ]; then
            # Move the contents of the 'out' directory to the root
            mv out/* .
            mv out/.* . || true  # Move hidden files if any
          else
            echo "Error: 'out' directory does not exist."
            exit 1
          fi
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Deploy site from out directory'
          git push -u origin HEAD:gh-pages --force
